---
- name: Create new ACME Corp release
  hosts: controller.acme.example.com
  gather_facts: false

  tasks:
    - name: Create new ACME release
      ansible.builtin.uri:
        url: "{{ repo_url }}/api/v1/repos/{{ student_user }}/acme_corp/releases"
        method: POST
        user: "{{ student_user }}"
        password: "{{ student_password }}"
        body_format: json
        force_basic_auth: true
        body:
          '{"target_commitish": "main",
          "name": "ACME Corp Patch Release {{ tag_name }}",
          "draft": false,
          "prerelease": false,
          "tag_name": "{{ tag_name }}"}'
        status_code: 201
      register: __result
      until: __result.status == 201
      retries: 3
      delay: 3
      tags:
        - create-release
