---
- name: Gather system information
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Gather recent vmstat info
      ansible.builtin.command: vmstat 1 5
      register: vmstat
      changed_when: false

    - name: Gather top CPU hogs
      ansible.builtin.command: ps -eo user,pid,size,pcpu,cmd --sort=-pcpu
      register: pscpu
      changed_when: false

    - name: Gather top memory hogs
      ansible.builtin.command: ps -eo user,pid,size,pcpu,cmd --sort=-size
      register: pssize
      changed_when: false

    - name: Swap + wait states
      ansible.builtin.debug:
        var: vmstat.stdout_lines

    - name: Top 3 CPU hogs
      ansible.builtin.debug:
        var: pscpu.stdout_lines[:4]

    - name: Top 3 memory hogs
      ansible.builtin.debug:
        var: pssize.stdout_lines[:4]
