---
- name: Setup Dublin hop node
  hosts: all
  gather_facts: false

  tasks:
  - name: Configure mesh on hop node
    ansible.builtin.service:
      name: receptor
      state: started

  - name: Get hop node status
    ansible.builtin.command: >
      receptorctl --socket /var/run/awx-receptor/receptor.sock status
    register: hop_status
    changed_when: false
    until: hop_status.stdout.find('mesh-automation-controller') != -1
    delay: 5
    retries: 15

  - name: Print mesh node status
    ansible.builtin.debug:
      var: hop_status.stdout_lines[:13]

