---
- name: Setup Dublin hop node
  hosts: all
  gather_facts: false
  become: true

  tasks:
  - name: Configure Dublin mesh hop node
    service:
      name: receptor
      state: started
   
  - name: Get Dublin hop node status
    command: >
      receptorctl --socket /var/run/awx-receptor/receptor.sock status
    register: hop_status

  - name: Print Dublin hop node status
    ansible.builtin.debug:
      var: hop_status.stdout_lines[:13]