---
- name: Configure firewall for monitoring
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Configure firewall for monitoring
      vars:
        firewall:
          - set_default_zone: internal
            state: enabled
            permanent: true
          - service: cockpit
            state: enabled
            permanent: true
            zone: internal
          - port: 27199/tcp
            state: enabled
            permanent: true
            zone: internal
          - port: 8088/tcp
            state: enabled
            permanent: true
            zone: internal
      ansible.builtin.import_role:
        name: linux-system-roles.firewall
    
    # - name: Reload edge application
    #   ansible.builtin.service:
    #     name: afiot-inductive-automation-ignition
    #     state: restarted

    

